### ISSUE TITLE
rpi: Getting this to work

### ISSUE THREAD

**Issue by jpvalery** [jpvalery/outline#1]
```
pi@raspberrypi:~/outline $ docker-compose up --force-recreate
Building outline
Sending build context to Docker daemon  6.011MB
Step 1/29 : ARG APP_PATH=/opt/outline
Step 2/29 : FROM arm64v8/node:14-alpine AS deps-common
 ---> 7a0c075c0bf6
Step 3/29 : ARG APP_PATH
 ---> Using cache
 ---> 72718871f006
Step 4/29 : WORKDIR $APP_PATH
 ---> Using cache
 ---> e530aa9565a8
Step 5/29 : COPY ./package.json ./yarn.lock ./
 ---> Using cache
 ---> 77767fdaf20d
Step 6/29 : FROM deps-common AS deps-dev
 ---> 77767fdaf20d
Step 7/29 : RUN yarn install --no-optional --frozen-lockfile &&   yarn cache clean
 ---> [Warning] The requested image's platform (linux/arm64/v8) does not match the detected host platform (linux/arm/v7) and no specific platform was requested
 ---> Running in d4d4505d2c1d
standard_init_linux.go:228: exec user process caused: exec format error
The command '/bin/sh -c yarn install --no-optional --frozen-lockfile &&   yarn cache clean' returned a non-zero code: 1
ERROR: Service 'outline' failed to build : Build failed
```

Running on Raspberry Pi 3 B. 

Don't know what is going wrong—The issue clearly is in https://github.com/jpvalery/outline/blob/rpi/Dockerfile but can't figure it out yet

**Comment by jpvalery** [comment]
https://forums.docker.com/t/daemon-error-responses-exec-format-error-and-container-is-restarting-wait-until-the-container-is-running/110385/4 Is it because the outline image doesn't have a arm version? But how is it running on https://github.com/outline/outline/discussions/1936#discussioncomment-1346036 then

**Comment by jpvalery** [comment]
https://forums.docker.com/t/daemon-error-responses-exec-format-error-and-container-is-restarting-wait-until-the-container-is-running/110385/4 Is it because the outline image doesn't have a arm version which I then realized was the exact same issue that started https://github.com/outline/outline/discussions/1936#discussioncomment-1346036 🤦

**Comment by jpvalery** [comment]
Finally found some workarounds but the build crashes—maybe the pi 3b is not strong enough for this?
```
Step 15/29 : RUN yarn build
 ---> Running in eb7d4fbd4e90
yarn run v1.22.5
$ yarn clean && yarn build:webpack && yarn build:i18n && yarn build:server
$ rimraf build
$ webpack --config webpack.config.prod.js

<--- Last few GCs --->

[65:0x501c110]   408790 ms: Mark-sweep (reduce) 228.2 (232.0) -> 227.8 (232.3) MB, 1591.7 / 0.0 ms  (average mu = 0.110, current mu = 0.010) allocation failure scavenge might not succeed
[65:0x501c110]   410225 ms: Mark-sweep (reduce) 228.5 (232.0) -> 228.0 (232.6) MB, 1419.4 / 0.0 ms  (average mu = 0.061, current mu = 0.011) allocation failure scavenge might not succeed


<--- JS stacktrace --->

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
^[[A^[[AAborted (core dumped)
error Command failed with exit code 134.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 134.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
The command '/bin/sh -c yarn build' returned a non-zero code: 134
ERROR: Service 'outline' failed to build : Build failed

```

**Comment by jpvalery** [comment]
Received and setup a RPI4 which helped pass over this first issue. 

Now getting a new error:
```
Step 26/29 : RUN addgroup -g 1001 -S nodejs &&   adduser -S nodejs -u 1001 &&   chown -R nodejs:nodejs $APP_PATH/build
 ---> Running in 4df0b54fa04b
Option g is ambiguous (gecos, gid, group)
Option s is ambiguous (shell, system)
adduser [--home DIR] [--shell SHELL] [--no-create-home] [--uid ID]
[--firstuid ID] [--lastuid ID] [--gecos GECOS] [--ingroup GROUP | --gid ID]
[--disabled-password] [--disabled-login] [--add_extra_groups] USER
   Add a normal user

adduser --system [--home DIR] [--shell SHELL] [--no-create-home] [--uid ID]
[--gecos GECOS] [--group | --ingroup GROUP | --gid ID] [--disabled-password]
[--disabled-login] [--add_extra_groups] USER
   Add a system user

adduser --group [--gid ID] GROUP
addgroup [--gid ID] GROUP
   Add a user group

addgroup --system [--gid ID] GROUP
   Add a system group

adduser USER GROUP
   Add an existing user to an existing group

general options:
  --quiet | -q      don't give process information to stdout
  --force-badname   allow usernames which do not match the
                    NAME_REGEX configuration variable
  --help | -h       usage message
  --version | -v    version number and copyright
  --conf | -c FILE  use FILE as configuration file

The command '/bin/sh -c addgroup -g 1001 -S nodejs &&   adduser -S nodejs -u 1001 &&   chown -R nodejs:nodejs $APP_PATH/build' returned a non-zero code: 1
ERROR: Service 'outline' failed to build : Build failed
```

**Comment by jpvalery** [comment]
c8d3456 cleared the error

**Comment by jpvalery** [comment]
docker-compose completes but now facing:
```
outline_1   | yarn run v1.22.5
postgres_1  | performing post-bootstrap initialization ... ok
outline_1   | $ node ./build/server/index.js
outline_1   | internal/modules/cjs/loader.js:892
outline_1   |   throw err;
outline_1   |   ^
outline_1   | 
outline_1   | Error: Cannot find module '/opt/outline/build/server/index.js'
outline_1   |     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:889:15)
outline_1   |     at Function.Module._load (internal/modules/cjs/loader.js:745:27)
outline_1   |     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)
outline_1   |     at internal/main/run_main_module.js:17:47 {
outline_1   |   code: 'MODULE_NOT_FOUND',
outline_1   |   requireStack: []
outline_1   | }
outline_1   | error Command failed with exit code 1.
outline_1   | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by jpvalery** [comment]
c42fa06 might have fixe this above but a new error surfaced:
```
outline_1   | yarn run v1.22.5
outline_1   | $ node ./build/server/index.js
outline_1   | internal/validators.js:124
outline_1   |     throw new ERR_INVALID_ARG_TYPE(name, 'string', value);
outline_1   |     ^
outline_1   | 
outline_1   | TypeError [ERR_INVALID_ARG_TYPE]: The "url" argument must be of type string. Received undefined
outline_1   |     at validateString (internal/validators.js:124:11)
outline_1   |     at Url.parse (url.js:170:3)
outline_1   |     at Object.urlParse [as parse] (url.js:157:13)
outline_1   |     at new Sequelize (/opt/outline/node_modules/sequelize/lib/sequelize.js:185:28)
outline_1   |     at Object.<anonymous> (/opt/outline/build/server/sequelize.js:26:19)
outline_1   |     at Module._compile (internal/modules/cjs/loader.js:1072:14)
outline_1   |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
outline_1   |     at Module.load (internal/modules/cjs/loader.js:937:32)
outline_1   |     at Function.Module._load (internal/modules/cjs/loader.js:778:12)
outline_1   |     at Module.require (internal/modules/cjs/loader.js:961:19)
outline_1   |     at require (internal/modules/cjs/helpers.js:92:18)
outline_1   |     at Object.<anonymous> (/opt/outline/build/server/models/ApiKey.js:10:18)
outline_1   |     at Module._compile (internal/modules/cjs/loader.js:1072:14)
outline_1   |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
outline_1   |     at Module.load (internal/modules/cjs/loader.js:937:32)
outline_1   |     at Function.Module._load (internal/modules/cjs/loader.js:778:12) {
outline_1   |   code: 'ERR_INVALID_ARG_TYPE'
outline_1   | }
outline_1   | error Command failed with exit code 1.
outline_1   | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
outline_outline_1 exited with code 1
```

**Comment by jpvalery** [comment]
FWIW: tried cloning https://github.com/manojchandrashekar/outline directly to see if it'd run—it didn't. Bummer.

**Comment by jpvalery** [comment]
Trying a completely different route with https://github.com/chsasank/outline-wiki-docker-compose but running into a nginx issue— reviving an old issue https://github.com/chsasank/outline-wiki-docker-compose/issues/9 to see what could be going wrong
